/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'title' : string,
  'date' : Time,
  'imageUrl' : string,
  'excerpt' : string,
  'category' : string,
}
export interface ContactFormSubmission {
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addBlogPost' : ActorMethod<[string, string, string, string], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactFormSubmission>>,
  'getBlogPostsByCategory' : ActorMethod<[string], Array<BlogPost>>,
  'getSortedBlogPostsByDate' : ActorMethod<[], Array<BlogPost>>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];